### ISSUE TITLE
install error [MinGW]

### ISSUE THREAD

**Issue by LXP-Never** [DavidDiazGuerra/gpuRIR#14]
pip install https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
Collecting https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
  Using cached https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
Installing collected packages: gpuRIR
  Running setup.py install for gpuRIR ... error
    Complete output from command C:\Users\Never\Desktop\TAC-master\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Never\\AppData\\Local\\Temp\\pip-req-build-7ze1k7yk\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Never\AppData\Local\Temp\pip-record-l14xf53f\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Never\Desktop\TAC-master\venv\include\site\python3.6\gpuRIR:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\gpuRIR
    copying gpuRIR\__init__.py -> build\lib.win-amd64-3.6\gpuRIR
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:5 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Never/AppData/Local/Temp/pip-req-build-7ze1k7yk/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Never\AppData\Local\Temp\pip-req-build-7ze1k7yk\setup.py", line 86, in <module>
        "Operating System :: OS Independent",
      File "C:\Users\Never\Desktop\TAC-master\venv\lib\site-packages\setuptools-40.8.0-py3.6.egg\setuptools\__init__.py", line 145, in setup
      File "D:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Never\Desktop\TAC-master\venv\lib\site-packages\setuptools-40.8.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "D:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Never\AppData\Local\Temp\pip-req-build-7ze1k7yk\setup.py", line 37, in run
        self.build_extension(ext)
      File "C:\Users\Never\AppData\Local\Temp\pip-req-build-7ze1k7yk\setup.py", line 61, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "D:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Never\\AppData\\Local\\Temp\\pip-req-build-7ze1k7yk', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Never\\AppData\\Local\\Temp\\pip-req-build-7ze1k7yk\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\Never\\Desktop\\TAC-master\\venv\\Scripts\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Never\\AppData\\Local\\Temp\\pip-req-build-7ze1k7yk\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

**Comment by LXP-Never** [comment]
window 10
cuda 10.0
python 3.6
cmake 3.12.0
GCC version 8.1

**Comment by DavidDiazGuerra** [comment]
Thanks for reporting the bug.

When I tested the library on Windows I compiled it with MSVC++, I think your bug is due to be using MinGW's GCC. I'll try to update CMakeLists.txt in order to make it compatible with MinGW in the following days.

Regards,
David

**Comment by LXP-Never** [comment]
> 感谢您报告错误。
> 
> 当我在Windows上测试该库时，我使用MSVC ++对其进行了编译，我认为您的错误是由于使用了MinGW的GCC。我将尝试更新CMakeLists.txt，以使其在接下来的几天中与MinGW兼容。
> 
> 问候，
> 大卫

thank you very much

**Comment by DavidDiazGuerra** [comment]
I've been tacking a look at this issue and it seems like it isn't a good idea using CUDA with MinGW, all the information I found from Nvidia encourages using the MSVC compiler in Windows instead of GCC (which is encouraged for Linux). 

How did you install CUDA in your Windows 10 computer? Did you followed a specific guide for MinGW or did you follow [the original installation guide](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html)?

**Comment by LXP-Never** [comment]
> MSVC compiler

I will consider using the MSVC compiler

**Comment by DavidDiazGuerra** [comment]
I think Tensorflow for Windows is compiled using MSVC, so you will need to compile gpuRIR with it if you want to be able to import both modules in the same Python project.

**Comment by LXP-Never** [comment]
> I think Tensorflow for Windows is compiled using MSVC, so you will need to compile gpuRIR with it if you want to be able to import both modules in the same Python project.
All right, thank you very much！I'm going to use MSVC compiler

**Comment by DavidDiazGuerra** [comment]
You're welcome. Let me know if you have any issue using MSVC.

**Comment by LXP-Never** [comment]
Failed building wheel for gpuRIR
  Running setup.py clean for gpuRIR
Failed to build gpuRIR
Installing collected packages: gpuRIR
  Running setup.py install for gpuRIR ... error
    Complete output from command D:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\98453\\AppData\\Local\\Temp\\pip-req-build-dlpdgxgx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\98453\AppData\Local\Temp\pip-record-0bgls13e\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\gpuRIR
    copying gpuRIR\__init__.py -> build\lib.win-amd64-3.6\gpuRIR
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
    -- The CXX compiler identification is MSVC 19.26.28806.0
    CMake Error at D:/ProgramData/Anaconda3/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:365 (message):
      No CUDA toolset found.
    Call Stack (most recent call first):
      D:/ProgramData/Anaconda3/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
      D:/ProgramData/Anaconda3/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
      CMakeLists.txt:5 (project)


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/98453/AppData/Local/Temp/pip-req-build-dlpdgxgx/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\98453\AppData\Local\Temp\pip-req-build-dlpdgxgx\setup.py", line 86, in <module>
        "Operating System :: OS Independent",
      File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "D:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\98453\AppData\Local\Temp\pip-req-build-dlpdgxgx\setup.py", line 37, in run
        self.build_extension(ext)
      File "C:\Users\98453\AppData\Local\Temp\pip-req-build-dlpdgxgx\setup.py", line 61, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "D:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\98453\\AppData\\Local\\Temp\\pip-req-build-dlpdgxgx', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\98453\\AppData\\Local\\Temp\\pip-req-build-dlpdgxgx\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=D:\\ProgramData\\Anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\98453\\AppData\\Local\\Temp\\pip-req-build-dlpdgxgx\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

**Comment by LXP-Never** [comment]
A new problem has arisen

**Comment by DavidDiazGuerra** [comment]
CMake is not able to find your CUDA toolset... What did you install first? Visual Studio or CUDA? There seems to be some kind of bug if you install CUDA before VS: https://stackoverflow.com/questions/61300669/windows-cmake-error-no-cuda-toolset-found, https://stackoverflow.com/questions/56636714/cuda-compile-problems-on-windows-cmake-error-no-cuda-toolset-found

Maybe another option would be to specify the CUDA location in the CMake GUI https://stackoverflow.com/questions/44724849/cmake-3-4-3-cant-find-cuda-on-windows but I'm not sure if this would work in you case.

**Comment by DavidDiazGuerra** [comment]
I am not going to implement MinGW's GCC support for Windows since NVidia encourages using MSVC instead. The second error seems to be related with your installation not with the library itself.  Therefore, I'm closeing this issue.
