### ISSUE TITLE
ImportError: DLL load failed while importing gpuRIR_bind: The specified module could not be found.

### ISSUE THREAD

**Issue by qdhanxiao** [DavidDiazGuerra/gpuRIR#30]
Hi David,

I want to use the gpuRIR library to generate a dataset for doing beamforming. I successfully installed gpuRIR on my laptop, but I keep getting this error when I run the code. I have tried many solutions to similar errors, but I have not been able to solve this problem, and I have not seen anyone else encountering this error about the gpuRIR library on the Internet. Hope to get your help, thank you!

Regards
Xiao

**Comment by DavidDiazGuerra** [comment]
Hi Xiao,

That error is weird, all the DLLs needed should have been generated during the installation. How did you install the library? Did you get any error or warning message while doing it?

Best regards,
David

**Comment by yang-china** [comment]
Hi David,
I keep getting this error when I run the code,and not install the library.
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-req-build-opp33xvm\setup.py", line 86, in <module>
        "Operating System :: OS Independent",
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\site-packages\setuptools\command\install.py", line 68, in run
        return orig.install.run(self)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\admin\AppData\Local\Temp\pip-req-build-opp33xvm\setup.py", line 37, in run
        self.build_extension(ext)
      File "C:\Users\admin\AppData\Local\Temp\pip-req-build-opp33xvm\setup.py", line 62, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "C:\Users\admin\.conda\envs\DeepLearning36\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\admin\.conda\envs\DeepLearning36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-req-build-opp33xvm\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-req-build-opp33xvm\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-a8ikwxpw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\admin\.conda\envs\DeepLearning36\Include\gpuRIR' Check the logs for full command output.

**Comment by DavidDiazGuerra** [comment]
Hi Yang,

I think your error is completely different than the original one, so I think it would be better to open a new issue for it.

If I understood correctly, the error occurs when you're trying to install the library, how are you installing it? With `pip install https://github.com/DavidDiazGuerra/gpuRIR/zipball/master` I guess? It seems like CMake is not being able to compile the C++ and CUDA code, but I can't see what caused the error, do you have more logs? If there's all the information you get when installing the library with pip, maybe you could try to clone the repository and install the library with `python setup.py install`, I think you might get more logs in this way.

From the logs you reported, I guess you're using Windows. It's been some time since I don't use the library in Windows but I think it should work.

Best regards,
David
