### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by TungyuYoung** [DavidDiazGuerra/gpuRIR#51]
I tried to install gpurir by cloning the repository and running python setup.py install in an activated anaconda environment. Than error happened:
`running install
/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating gpuRIR.egg-info
writing gpuRIR.egg-info/PKG-INFO
writing dependency_links to gpuRIR.egg-info/dependency_links.txt
writing top-level names to gpuRIR.egg-info/top_level.txt
writing manifest file 'gpuRIR.egg-info/SOURCES.txt'
reading manifest file 'gpuRIR.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'gpuRIR.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-37
creating build/lib.linux-x86_64-cpython-37/gpuRIR
copying gpuRIR/__init__.py -> build/lib.linux-x86_64-cpython-37/gpuRIR
running build_ext
-- The CXX compiler identification is GNU 7.5.0
CMake Error at /home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:180 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    "Operating System :: OS Independent",
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 37, in run
    self.build_extension(ext)
  File "setup.py", line 61, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/tungyu/anaconda3/envs/ambi/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/tungyu/Project/gpuRIR/gpuRIR', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/tungyu/Project/gpuRIR/gpuRIR/build/lib.linux-x86_64-cpython-37', '-DPYTHON_EXECUTABLE=/home/tungyu/anaconda3/envs/ambi/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
(ambi) root@tungyu-1080:/home/tungyu/Project/gpuRIR/gpuRIR# bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
(ambi) root@tungyu-1080:/home/tungyu/Project/gpuRIR/gpuRIR# make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`
The os system is Ubuntu18.04.

**Comment by DavidDiazGuerra** [comment]
It seems like CMake is unable to find your CUDA installation needed to compile the library. Do you have the CUDA toolkit installed?

**Comment by TungyuYoung** [comment]
> It seems like CMake is unable to find your CUDA installation needed to compile the library. Do you have the CUDA toolkit installed?

I believe I have. But the CUDA toolkit is not installed on the system but the conda environment. I installed it by:
`# create a conda environment and install requirements

conda create -n ambi python=3.7
conda activate ambi
conda install pytorch==1.9.0 cudatoolkit=10.2 -c pytorch
conda install -c anaconda numpy
...
...
`

**Comment by DavidDiazGuerra** [comment]
I'm not sure if that's really enough to compile the library... or at least I've never tried it. Can you try to run the command `nvcc` to see if it is installed and, in case it is, run `which nvcc` to see where?
