### ISSUE TITLE
The cuda

### ISSUE THREAD

**Issue by TuttiChi** [DavidDiazGuerra/gpuRIR#54]
My env is Ubuntu 20.04. 3090Ti and CUDA 12.1.When I run the gpuRIR ,it occurs.

```Traceback (most recent call last):
  File "./ROOMA.py", line 12, in <module>
    import gpuRIR
  File "/home/tutti/anaconda3/envs/GPURIR/lib/python3.6/site-packages/gpuRIR-1.2.0-py3.6-linux-x86_64.egg/gpuRIR/__init__.py", line 9, in <module>
    from gpuRIR_bind import gpuRIR_bind
ImportError: /home/tutti/anaconda3/envs/GPURIR/lib/python3.6/site-packages/gpuRIR-1.2.0-py3.6-linux-x86_64.egg/gpuRIR_bind.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cufftExecC2R```

**Comment by TuttiChi** [comment]
> This seems to be the same issue as #50. I do not know why some installations are having problems finding the cuFFT library, I have never had this problem myself.

I see. I 'll close this question. Thank you very much!
