### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by xlzhou01** [DavidDiazGuerra/gpuRIR#55]
Hi, I'm getting the following error when I do pip setup.y install. I'm using the ubuntu system. And I installed cudatoolkit (version 10.2.89) and don't know how to fix this.
running build_ext
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/data/zhouxiaolong/TF-FaSNet/gpuRIR-master/gpuRIR-master/build/temp.linux-x86_64-cpython-37/CMakeFiles/CMakeOutput.log".
See also "/data/zhouxiaolong/TF-FaSNet/gpuRIR-master/gpuRIR-master/build/temp.linux-x86_64-cpython-37/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    "Operating System :: OS Independent",
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 37, in run
    self.build_extension(ext)
  File "setup.py", line 61, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/data/zhouxiaolong/TF-FaSNet/gpuRIR-master/gpuRIR-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/zhouxiaolong/TF-FaSNet/gpuRIR-master/gpuRIR-master/build/lib.linux-x86_64-cpython-37', '-DPYTHON_EXECUTABLE=/data/zhouxiaolong/miniconda3/envs/TF_FaSNet/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by DavidDiazGuerra** [comment]
Hello, it seems like CMake is struggling to find your CUDA installation. You could try to find the path yourself with `which nvcc` and then indicate it in the environment variable suggested in the error log with `export CUDACXX=path_to_cuda_compiler`.

**Comment by xlzhou01** [comment]
But in my virtual environment I have cudatoolkit, but typing which nvcc doesn't get any reply, is it a question of my version.
cudatoolkit==10.2.89
cmake==3.12.0

**Comment by DavidDiazGuerra** [comment]
I guess you installed the CUDA toolkit using conda instead of following the instructions on the NVidia website. I've never installed gpuRIR like that, I don't even know if it's possible. Some people here are suggesting installing `cudatoolkit-dev` instead of just `cudatoolkit`, I don't know if that will help: https://stackoverflow.com/questions/56470424/nvcc-missing-when-installing-cudatoolkit

**Comment by xlzhou01** [comment]
So how did you install cudatoolkit? (I searched it from Nvidia's official website, but it requires system administrator permissions（such as sudu command）, and I use a school shared server, so I don't have system permissions). Then I tried cudatoolkit-dev as well, but I couldn't install it. Sorry for your help.

**Comment by DavidDiazGuerra** [comment]
Installing the cudatoolkit without root access is indeed a bit tricky, but there are some guides online that might help. Anyway, I would try to contact the server administrators before trying anything myself, if the server has a GPU maybe the cudatoolkit is already installed or they can install it for you.

**Comment by xlzhou01** [comment]
I installed cuda-nvcc (version=11.3) by some means.but I tried using python setup.py install again and he got the error below.
![image](https://github.com/DavidDiazGuerra/gpuRIR/assets/145009606/8a46d137-8297-477e-b54c-6b584a83566a)

**Comment by DavidDiazGuerra** [comment]
I think the CMake version is okay, the problem seems to be with the CUDA compiler, but I'm afraid I cannot really help with that.

**Comment by xlzhou01** [comment]
Thank you for helping me in the past.
